language: php

php:
  - 5.5

mysql:
  database: dkan_travis
  username: root
  encoding: utf8

install:
  - mysql -e 'create database dkan_travis;'
  - sudo apt-get update > /dev/null
  - sudo apt-get --quiet=2 install php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:dev-master
  - composer global require --no-interaction youngj/httpserver:*

before_script:
  # Install DKAN
  - cd ~
  - git clone https://github.com/NuCivic/dkan-drops-7.git
  - cd dkan-drops-7

  - drush si dkan --sites-subdir=default --db-url=mysql://root:@127.0.0.1:3306/dkan_travis --account-name=admin --account-pass=admin  --site-name="DKAN" install_configure_form.update_status_module='array(FALSE,FALSE)' --yes
  - drush cc all --yes
  - cp -r /home/travis/build/NuCivic/leaflet_widget sites/all/modules/.
  - drush en -y migrate
  - cd sites/all/modules
  - git clone https://github.com/jacintocapote/leaflet_widget_us.git
  - drush en -y leaflet_widget
  - drush en -y leaflet_widget_us
  - cd leaflet_widget/test
  - composer install

script:
  - bin/behat
